### ISSUE TITLE
Question about 'de novo' meaning

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/trgt-denovo#2]
Hi,
Is this tool designed to detect de novo mutations, i.e. mutations in the child that are not inherited from the parents? Or is the meaning of 'de novo' referring to detection of repeat expansions that are not in one of the known repeat expansion genes associated with disease?

Thanks

**Comment by tmokveld** [comment]
Hello, thank you for your interest! The intended purpose of TRGT-denovo is to detect de novo mutations not inherited from either of the parents. Where a potential application is to cast a net as wide as possible, using large repeat catalogs, to survey not only repeat expansion genes associated with disease but also attempt to discover new ones.
