### ISSUE TITLE
malformed tarball

### ISSUE THREAD

**Issue by jrharting** [PacificBiosciences/trgt-denovo#3]
hi Tom,

I am unable to decompress the latest release (v0.2.0):

```
% gzip -d trgt-denovo-v0.2.0-x86_64-unknown-linux-gnu.tar.gz
gzip: trgt-denovo-v0.2.0-x86_64-unknown-linux-gnu.tar.gz: unexpected end of file
```

**Comment by tmokveld** [comment]
Hi John, you should be able to extract it with: `tar xvf trgt-denovo-v0.2.0-x86_64-unknown-linux-gnu.tar.gz`.

**Comment by jrharting** [comment]
my bad -- the download link was incorrect and the file was empty.  i was able to figure it out right after posting the issue 🤦 
  
thanks, Tom!
